name: home_automation_iot
description: Home Automation IoT Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# -------------------- DEPENDENCIES --------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

# -------------------- DEV DEPENDENCIES --------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # IMPORTANT (for app icon)
  flutter_launcher_icons: ^0.13.1


# -------------------- APP ICON CONFIG --------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  # (optional but recommended modern icon)
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"


# -------------------- FLUTTER --------------------
flutter:
  uses-material-design: true

  assets:
    - assets/
